<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>MariaDB Knowledge Base Comments for: DLL load failed while importing mariadb: Das angegebene Modul wurde nicht gefunden</title><link>https://mariadb.com/kb/en/mariadb-connectorpython-release-notes-dll-load-failed-while-importing-maria/+comments/feed/</link><description></description><atom:link href="https://mariadb.com/kb/en/mariadb-connectorpython-release-notes-dll-load-failed-while-importing-maria/+comments/feed/" rel="self"></atom:link><language>en-us</language><lastBuildDate>Mon, 27 Jan 2025 11:34:55 +0000</lastBuildDate><item><title>Re: DLL load failed while importing mariadb: Das angegebene Modul wurde nicht gefunden</title><link>https://mariadb.com/kb/en/mariadb-connectorpython-release-notes-dll-load-failed-while-importing-maria/+comments/4529</link><description>&lt;p&gt;see &lt;a href="https://jira.mariadb.org/browse/CONPY-66"&gt;https://jira.mariadb.org/browse/CONPY-66&lt;/a&gt;. I was able to reproduce it with Python3.8 only.&lt;/p&gt;
</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Georg Richter</dc:creator><guid>https://mariadb.com/kb/en/mariadb-connectorpython-release-notes-dll-load-failed-while-importing-maria/+comments/4529</guid></item></channel></rss>