<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>MariaDB Knowledge Base Comments for: Percona XtraBackup Overview</title><link>https://mariadb.com/kb/en/percona-xtrabackup-overview/+comments/feed/</link><description></description><atom:link href="https://mariadb.com/kb/en/percona-xtrabackup-overview/+comments/feed/" rel="self"></atom:link><language>en-us</language><lastBuildDate>Mon, 07 Oct 2024 03:13:55 +0000</lastBuildDate><item><title>Re: XtraBackup</title><link>https://mariadb.com/kb/en/percona-xtrabackup-overview/+comments/1025</link><description>&lt;p&gt;If you are getting errors like this &lt;/p&gt;
&lt;pre&gt;
140208 23:23:03 [Note] Found 1 prepared transaction(s) in InnoDB
140208 23:23:03 [ERROR] Found 1 prepared transactions! It means that mysqld was not shut down properly last time and critical recovery information (last binlog or tc.log file) was manually deleted after a crash. You have to start mysqld with --tc-heuristic-recover switch to commit or rollback pending transactions.
140208 23:23:03 [ERROR] Aborting
&lt;/pre&gt;
&lt;p&gt;while using XtraBackup with &lt;a href="/kb/en/what-is-mariadb-55/"&gt;MariaDB 5.5&lt;/a&gt; or higher, you most likely need to upgrade XtraBackup to a 2.1.7+ version. See more details in &lt;a href="https://bugs.launchpad.net/percona-xtrabackup/+bug/1254227"&gt;the bug report&lt;/a&gt;. Also, please note that the last comment there of 2014-01-06 about multiple XA engines can be easily misunderstood. The problem can appear even if you are not using any other XA-capable engines. &lt;/p&gt;
</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Elena Stepanova</dc:creator><guid>https://mariadb.com/kb/en/percona-xtrabackup-overview/+comments/1025</guid></item></channel></rss>